#ifndef DOCKLEA_H
#define DOCKLEA_H

#include <QDockWidget>

namespace Ui {
class DockLea;
}

class DockLea : public QDockWidget
{
    Q_OBJECT

public:
    enum class CW_SP_Data{TIMEBASE, TLEA, FORMULALEA, LEA_VALUE, TPOWERERGCOND_1, POWERERGCOND_1, TPOWERERGCOND_3, POWERERGCOND_3,
                          COUPLINGFACTOR1, COUPLINGFACTOR3, DIAMETERCOND1, DIAMETERCOND3, DISTANCECOND1, DISTANCECOND3,
                          BEAMATSTOPCOND1, BEAMATSTOPCOND3, CLASS};
    enum class MP_SP_Data{TIMEBASE, TE, TI, TI_PRF, MEANPOWER, PULSENUMBER, COUNTING, C5, TLEA, FORMULALEA, LEA_VALUE,
                          TPOWERERGCOND_1, POWERERGCOND_1, TPOWERERGCOND_3, POWERERGCOND_3, COUPLINGFACTOR1, COUPLINGFACTOR3,
                          DIAMETERCOND1, DIAMETERCOND3, DISTANCECOND1, DISTANCECOND3, BEAMATSTOPCOND1, BEAMATSTOPCOND3,
                          CLASS};
    enum class MP_Mean_Data{TMEANLEA=24, MEANFORMULALEA, MEANLEA_VALUE, TMEANPOWERERGCOND_1, MEANPOWERERGCOND_1, TMEANPOWERERGCOND_3,
                          MEANPOWERERGCOND_3, MEANCOUPLINGFACTOR1, MEANCOUPLINGFACTOR3, MEANDIAMETERCOND1, MEANDIAMETERCOND3,
                          MEANDISTANCECOND1, MEANDISTANCECOND3, MEANBEAMATSTOPCOND1, MEANBEAMATSTOPCOND3, MEANCLASS,
                          SYSTEMCLASS};
    enum class MP_Thermal_Data{TTHERMALLEA_VALUE=41, THERMALFORMULALEA, THERMALLEA_VALUE, TTHERMALPOWERERGCOND_1,
                          THERMALPOWERERGCOND_1, TTHERMALPOWERERGCOND_3, THERMALPOWERERGCOND_3, THERMALCOUPLINGFACTOR1,
                          THERMALCOUPLINGFACTOR3, THERMALDIAMETERCOND1, THERMALDIAMETERCOND3, THERMALDISTANCECOND1,
                          THERMALDISTANCECOND3, THERMALBEAMATSTOPCOND1, THERMALBEAMATSTOPCOND3, THERMALCLASS};

    explicit DockLea(QWidget *parent = nullptr);
    ~DockLea();
    Ui::DockLea *ui;

private:

};

#endif // DOCKLEA_H
